---
title: "Events"
toc-location: left
---

## Upcoming

### 2026
::::: {.d-flex .justify-content-between}
<div>
**PsiNet sponsored session at AGU2026 in San Francisco! B087 - Terrestrial Ecosystem Hydraulics in a Changing World**

This session is sponsored by the PSInet research coordination network, which is preparing to release a database of plant water potential time series. Many of the sites in this new database are co-located with flux towers and SAPFLUXNET sites, which opens up the possibility for some interesting cross-network and cross-scale syntheses.  

Invited speakers: Ana Maria Restrepo Acevedo (West Virginia University) and Arthur Endsley (University of Montana)

</div>
::: {.text-end .text-nowrap}
San Francisco, California, **December**
:::
:::::
## Past

### 2025

::::: {.d-flex .justify-content-between}
<div>

PsiNet sponsored session at AGU2025 in New Orleans! "Terrestrial ecosystems hydraulics in a changing world."(B087)

Invited speakers include Andrew Feldman (NASA) and Jessica Guo (Harvey Mudd College).

Session info [here](https://agu.confex.com/agu/agu25/prelim.cgi/Session/248821)

</div>

::: {.text-end .text-nowrap}
New Orleans, Louisiana, **December 15 - 19**
:::
:::::

::::: {.d-flex .justify-content-between}
<div>

PSInet [workshop](https://psinetrcn.github.io/posts/2025-02-06-PSInet-workshop/post.html)! Apply [here](https://docs.google.com/forms/d/e/1FAIpQLSc2T5uVtZLR9rx0xipPs8aUOLxZSxjbaGl5HQoiMvuB3pdaIA/viewform) by March 10

</div>

::: {.text-end .text-nowrap}
Bloomington, Indiana, **June 23 - 27**
:::
:::::

## Archived Events

To see archived events, head here : [Previous Events](archive_events.qmd)